config/routes.rb
Conflictors::Application.routes.draw do
  resources :unobtrusive_jikochus

  resources :jikochus

end

app/models/jikochu.rb
class Jikochu < ActiveRecord::Base
  attr_accessible :fought_at, :name
end

app/models/unobtrusive_jikochu.rb
class UnobtrusiveJikochu < ActiveRecord::Base
  attr_accessible :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/jikochus_controller.rb
# -*- coding: utf-8 -*-
# GistID: 5023699
# Tried by: Rails 3.2.12

# 自己中な (Selfish) Controller
class JikochusController < ApplicationController

  def index
    @jikochus = Jikochu.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @jikochus }
    end
    #=> SystemStackError in JikochusController#index
    #=> stack level too deep
  end

  def request # 自己中な (selfish) request
    # 自己中なことにrequestを上書きしてしまう
    # 結果、他のアクションでも SystemStackError が起こる
    # It's as selfish as overriding the request method,
    # which causes SystemStackError in its other actions.
    render text: "どけどけどけー！オレのアクションだー！"
  end
end

app/controllers/unobtrusive_jikochus_controller.rb
# -*- coding: utf-8 -*-
# GistID: 5023809
# Tried by: Rails 3.2.12

# 控えめで (Unobtrusive) 自己中な (Selfish) Controller
class UnobtrusiveJikochusController < ApplicationController

  def index
    @unobtrusive_jikochus = UnobtrusiveJikochu.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @unobtrusive_jikochus }
    end
    #=> NoMethodError in UnobtrusiveJikochusController#index
    #=> undefined method `content_mime_type' for nil:NilClass
  end

  def request # 自己中な (selfish) request
    # 自己中なことにrequestを上書きしてしまう。
    # It's as selfish as overriding the request method.
    # でも控えめなので何もrenderしない。
    # but it's so unobtrusive that doesn't render anything.

    # 結果、NoMethodErrorとなる。
    # As a result, it causes NoMethodError.
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jikochus_helper.rb
module JikochusHelper
end

app/helpers/unobtrusive_jikochus_helper.rb
module UnobtrusiveJikochusHelper
end

app/views/jikochus/_form.html.erb
<%= form_for(@jikochu) do |f| %>
  <% if @jikochu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@jikochu.errors.count, "error") %> prohibited this jikochu from being saved:</h2>

      <ul>
      <% @jikochu.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :fought_at %><br />
    <%= f.datetime_select :fought_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jikochus/edit.html.erb
<h1>Editing jikochu</h1>

<%= render 'form' %>

<%= link_to 'Show', @jikochu %> |
<%= link_to 'Back', jikochus_path %>

app/views/jikochus/index.html.erb
<h1>Listing jikochus</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Fought at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @jikochus.each do |jikochu| %>
  <tr>
    <td><%= jikochu.name %></td>
    <td><%= jikochu.fought_at %></td>
    <td><%= link_to 'Show', jikochu %></td>
    <td><%= link_to 'Edit', edit_jikochu_path(jikochu) %></td>
    <td><%= link_to 'Destroy', jikochu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Jikochu', new_jikochu_path %>

app/views/jikochus/new.html.erb
<h1>New jikochu</h1>

<%= render 'form' %>

<%= link_to 'Back', jikochus_path %>

app/views/jikochus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @jikochu.name %>
</p>

<p>
  <b>Fought at:</b>
  <%= @jikochu.fought_at %>
</p>


<%= link_to 'Edit', edit_jikochu_path(@jikochu) %> |
<%= link_to 'Back', jikochus_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Conflictors</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/unobtrusive_jikochus/_form.html.erb
<%= form_for(@unobtrusive_jikochu) do |f| %>
  <% if @unobtrusive_jikochu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@unobtrusive_jikochu.errors.count, "error") %> prohibited this unobtrusive_jikochu from being saved:</h2>

      <ul>
      <% @unobtrusive_jikochu.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/unobtrusive_jikochus/edit.html.erb
<h1>Editing unobtrusive_jikochu</h1>

<%= render 'form' %>

<%= link_to 'Show', @unobtrusive_jikochu %> |
<%= link_to 'Back', unobtrusive_jikochus_path %>

app/views/unobtrusive_jikochus/index.html.erb
<h1>Listing unobtrusive_jikochus</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @unobtrusive_jikochus.each do |unobtrusive_jikochu| %>
  <tr>
    <td><%= unobtrusive_jikochu.name %></td>
    <td><%= link_to 'Show', unobtrusive_jikochu %></td>
    <td><%= link_to 'Edit', edit_unobtrusive_jikochu_path(unobtrusive_jikochu) %></td>
    <td><%= link_to 'Destroy', unobtrusive_jikochu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Unobtrusive jikochu', new_unobtrusive_jikochu_path %>

app/views/unobtrusive_jikochus/new.html.erb
<h1>New unobtrusive_jikochu</h1>

<%= render 'form' %>

<%= link_to 'Back', unobtrusive_jikochus_path %>

app/views/unobtrusive_jikochus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @unobtrusive_jikochu.name %>
</p>


<%= link_to 'Edit', edit_unobtrusive_jikochu_path(@unobtrusive_jikochu) %> |
<%= link_to 'Back', unobtrusive_jikochus_path %>